name: "eShulker"
version: ${version}
main: "dev.eyrond.shulker.ShulkerPlugin"
authors: [ "eyrond" ]
website: "https://eyrond.dev"
description: "Open shulkers right in your hands."
load: "STARTUP"
api-version: "1.20"
